name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Compile the code
      run: echo "Compiling the code..." && echo "Compile complete."

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Unit test
      run: echo "Running unit tests... This will take about 60 seconds." && sleep 60 && echo "Code coverage is 90%"

    - name: Lint test
      run: echo "Linting code... This will take about 10 seconds." && sleep 10 && echo "No lint issues found."

  deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: production
    needs: [test]

    steps:
    - name: Deploy application
      run: echo "Deploying application..." && echo "Application successfully deployed."
